### ISSUE TITLE
Build failed in awesome-typescript-loader

### ISSUE THREAD

**Issue by wadahiro** [wadahiro/bitbucket-browser#8]
```
ERROR in ./src/script/bulma/Utils.ts
Module build failed: Error: Unknown file d:\Users\wadahiro\src\github.com\wadahiro\bitbucket-browser\src\script\bulma\Utils.ts
    at State.fastEmit (d:\Users\wadahiro\src\github.com\wadahiro\bitbucket-browser\node_modules\awesome-typescript-loader\dist.babel\host.js:300:23)
    at transform (d:\Users\wadahiro\src\github.com\wadahiro\bitbucket-browser\node_modules\awesome-typescript-loader\dist.babel\index.js:215:53)
    at _callee3$ (d:\Users\wadahiro\src\github.com\wadahiro\bitbucket-browser\node_modules\awesome-typescript-loader\dist.babel\index.js:265:42)
    at tryCatch (d:\Users\wadahiro\src\github.com\wadahiro\bitbucket-browser\node_modules\regenerator-runtime\runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (d:\Users\wadahiro\src\github.com\wadahiro\bitbucket-browser\node_modules\regenerator-runtime\run
time.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (d:\Users\wadahiro\src\github.com\wadahiro\bitbucket-browser\node_modules\re
generator-runtime\runtime.js:95:21)
    at fulfilled (d:\Users\wadahiro\src\github.com\wadahiro\bitbucket-browser\node_modules\awesome-typescript-loader\dist.babel\index.js:31:32)
    at run (d:\Users\wadahiro\src\github.com\wadahiro\bitbucket-browser\node_modules\babel-polyfill\node_modules\core-js\modules\es6.promise.js:89:22)
    at d:\Users\wadahiro\src\github.com\wadahiro\bitbucket-browser\node_modules\babel-polyfill\node_modules\core-js\modules\es6.promise.js:102:28
    at flush (d:\Users\wadahiro\src\github.com\wadahiro\bitbucket-browser\node_modules\babel-polyfill\node_modules\core-js\modules\_microtask.js:18:9)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
 @ ./src/script/bulma/index.tsx 367:13-31
```

**Comment by wadahiro** [comment]
It looks like same error with 
https://github.com/AngularClass/angular2-webpack-starter/issues/687 .

> Going back to "~0.17.0" solved the problem.

I try to fix the version.
